const loginConstants = {
  LOGIN_LOADING: "LOGIN_LOADING",
  
  LOGIN_START: "LOGIN_START",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  
  LOGIN_MODAL_START: "LOGIN_MODAL_START",
  LOGIN_MODAL_TOGGLE: "LOGIN_MODAL_TOGGLE",
  LOGIN_MODAL_STOP: "LOGIN_MODAL_STOP"
};

export default loginConstants;
