const registerConstants = {
  REGISTER_LOADING: "REGISTER_LOADING",
  
  REGISTER_START: "REGISTER_START",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  
  REGISTER_MODAL_START: "REGISTER_MODAL_START",
  REGISTER_MODAL_TOGGLE: "REGISTER_MODAL_TOGGLE",
  REGISTER_MODAL_STOP: "REGISTER_MODAL_STOP"
};

export default registerConstants;
